### ISSUE TITLE
CustomNPC without plus

### ISSUE THREAD

**Issue by re7gog** [CrucibleMC/NecroTempus#9]
When running CustomNPC not plus version game crashes.
It would be nice if there was a notification about using the plus version, because I only realized this by looking at the git history.

Error:
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: noppes/npcs/client/renderer/RenderNPCPony
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by brunoxkk0** [comment]
The problem is in the boss bar, it tries to access the Faction class, but it is in another package in custom NPCs

**Comment by brunoxkk0** [comment]
We recommend using [Custom NPC+](https://github.com/KAMKEEL/CustomNPC-Plus). Integration with the standard CustomNPC is not planned.
